package generico;

/** Lista de Emojis */
public enum Emoji {
    // Faces - teste commit
    GRINNING_FACE               ('\uD83D','\uDE00'),
    INOCENT_FACE                ('\uD83D','\uDE07'),
    SMILING_IMP_FACE            ('\uD83D','\uDE08'),
    SUNGLASSES_FACE             ('\uD83D','\uDE0E'),
    NEUTRAL_FACE                ('\uD83D','\uDE10'),
    EXPRESSIONLESS_FACE         ('\uD83D','\uDE11'),
    CONFUSED_FACE               ('\uD83D','\uDE15'),
    KISSING_FACE                ('\uD83D','\uDE17'),
    KISSING_SMILING_EYES_FACE   ('\uD83D','\uDE19'),
    KISSING_CLOSED_EYES_FACE    ('\uD83D','\uDE1A'),
    STUCK_OUT_TONGUE_FACE       ('\uD83D','\uDE1B'),
    WORRIED_FACE                ('\uD83D','\uDE1F'),
    FROWNING_FACE               ('\uD83D','\uDE26'),
    ANGUISHED_FACE              ('\uD83D','\uDE27'),
    GRIMACING_FACE              ('\uD83D','\uDE2C'),
    OPEN_MOUTH_FACE             ('\uD83D','\uDE2E'),
    HUSHED_FACE                 ('\uD83D','\uDE2F'),
    SLEEPING_FACE               ('\uD83D','\uDE34'),
    NO_MOUTH_FACE               ('\uD83D','\uDE36'),
    SLIGHTLY_FROWNING_FACE      ('\uD83D','\uDE41'),
    SLIGHTLY_SMILING_FACE       ('\uD83D','\uDE42'),
    UPSIDE_DOWN_FACE            ('\uD83D','\uDE43'),
    ROLL_EYES_FACE              ('\uD83D','\uDE44'),

    // Faces Pt2
    // Emoticones group
    GRINNING_FACE_WITH_SMILING_EYES                     ('\uD83D', '\uDE01'),
    FACE_WITH_TEARS_OF_JOY                              ('\uD83D', '\uDE02'),
    SMILING_FACE_WITH_OPEN_MOUTH                        ('\uD83D', '\uDE03'),
    SMILING_FACE_WITH_OPEN_MOUTH_AND_SMILING_EYES       ('\uD83D', '\uDE04'),
    SMILING_FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT         ('\uD83D', '\uDE05'),
    SMILING_FACE_WITH_OPEN_MOUTH_AND_TIGHTLY_CLOSED_EYES('\uD83D', '\uDE06'),
    WINKING_FACE                                        ('\uD83D', '\uDE09'),
    SMILING_FACE_WITH_SMILING_EYES                      ('\uD83D', '\uDE0A'),
    FACE_SAVOURING_DELICIOUS_FOOD                       ('\uD83D', '\uDE0B'),
    RELIEVED_FACE                                       ('\uD83D', '\uDE0C'),
    SMILING_FACE_WITH_HEART_SHAPED_EYES                 ('\uD83D', '\uDE0D'),
    SMIRKING_FACE                                       ('\uD83D', '\uDE0F'),
    UNAMUSED_FACE                                       ('\uD83D', '\uDE12'),
    FACE_WITH_COLD_SWEAT                                ('\uD83D', '\uDE13'),
    PENSIVE_FACE                                        ('\uD83D', '\uDE14'),
    CONFOUNDED_FACE                                     ('\uD83D', '\uDE16'),
    FACE_THROWING_A_KISS                                ('\uD83D', '\uDE18'),
    KISSING_FACE_WITH_CLOSED_EYES                       ('\uD83D', '\uDE1A'),
    FACE_WITH_STUCK_OUT_TONGUE_AND_WINKING_EYE          ('\uD83D', '\uDE1C'),
    FACE_WITH_STUCK_OUT_TONGUE_AND_TIGHTLY_CLOSED_EYES  ('\uD83D', '\uDE1D'),
    DISAPPOINTED_FACE                                   ('\uD83D', '\uDE1E'),
    ANGRY_FACE                                          ('\uD83D', '\uDE20'),
    POUTING_FACE                                        ('\uD83D', '\uDE21'),
    CRYING_FACE                                         ('\uD83D', '\uDE22'),
    PERSEVERING_FACE                                    ('\uD83D', '\uDE23'),
    FACE_WITH_LOOK_OF_TRIUMPH                           ('\uD83D', '\uDE24'),
    DISAPPOINTED_BUT_RELIEVED_FACE                      ('\uD83D', '\uDE25'),
    FEARFUL_FACE                                        ('\uD83D', '\uDE28'),
    WEARY_FACE                                          ('\uD83D', '\uDE29'),
    SLEEPY_FACE                                         ('\uD83D', '\uDE2A'),
    TIRED_FACE                                          ('\uD83D', '\uDE2B'),
    LOUDLY_CRYING_FACE                                  ('\uD83D', '\uDE2D'),
    FACE_WITH_OPEN_MOUTH_AND_COLD_SWEAT                 ('\uD83D', '\uDE30'),
    FACE_SCREAMING_IN_FEAR                              ('\uD83D', '\uDE31'),
    ASTONISHED_FACE                                     ('\uD83D', '\uDE32'),
    FLUSHED_FACE                                        ('\uD83D', '\uDE33'),
    DIZZY_FACE                                          ('\uD83D', '\uDE35'),
    FACE_WITH_MEDICAL_MASK                              ('\uD83D', '\uDE37'),
    GRINNING_CAT_FACE_WITH_SMILING_EYES                 ('\uD83D', '\uDE38'),
    CAT_FACE_WITH_TEARS_OF_JOY                          ('\uD83D', '\uDE39'),
    SMILING_CAT_FACE_WITH_OPEN_MOUTH                    ('\uD83D', '\uDE3A'),
    SMILING_CAT_FACE_WITH_HEART_SHAPED_EYES             ('\uD83D', '\uDE3B'),
    CAT_FACE_WITH_WRY_SMILE                             ('\uD83D', '\uDE3C'),
    KISSING_CAT_FACE_WITH_CLOSED_EYES                   ('\uD83D', '\uDE3D'),
    POUTING_CAT_FACE                                    ('\uD83D', '\uDE3E'),
    CRYING_CAT_FACE                                     ('\uD83D', '\uDE3F'),
    WEARY_CAT_FACE                                      ('\uD83D', '\uDE40'),
    FACE_WITH_NO_GOOD_GESTURE                           ('\uD83D', '\uDE45'),
    FACE_WITH_OK_GESTURE                                ('\uD83D', '\uDE46'),
    PERSON_BOWING_DEEPLY                                ('\uD83D', '\uDE47'),
    SEE_NO_EVIL_MONKEY                                  ('\uD83D', '\uDE48'),
    HEAR_NO_EVIL_MONKEY                                 ('\uD83D', '\uDE49'),
    SPEAK_NO_EVIL_MONKEY                                ('\uD83D', '\uDE4A'),
    HAPPY_PERSON_RAISING_ONE_HAND                       ('\uD83D', '\uDE4B'),
    PERSON_RAISING_BOTH_HANDS_IN_CELEBRATION            ('\uD83D', '\uDE4C'),
    PERSON_FROWNING                                     ('\uD83D', '\uDE4D'),
    PERSON_WITH_POUTING_FACE                            ('\uD83D', '\uDE4E'),
    PERSON_WITH_FOLDED_HANDS                            ('\uD83D', '\uDE4F'),

    // Configs
    DIGIT_THREE          (null, '\u0033'),
    ALARM_CLOCK          (null, '\u23F0'),
    WARNING_SIGN         (null, '\u26a0'),
    LOW_BRIGHTNESS       ('\uD83D','\uDD05'),
    HIGH_BRIGHTNESS      ('\uD83D','\uDD06'),
    MUTE                 ('\uD83D','\uDD07'),
    SPEAKER              ('\uD83D','\uDD08'),
    SOUND                ('\uD83D','\uDD09'),
    LOUD_SOUND           ('\uD83D','\uDD0A'),
    BATTERY              ('\uD83D','\uDD0B'),
    ELECTRIC_PLUG        ('\uD83D','\uDD0C'),
    MAG                  ('\uD83D','\uDD0D'),
    MAG_RIGHT            ('\uD83D','\uDD0E'),
    LOCK_WITH_INK_PEN    ('\uD83D','\uDD0F'),
    CLOSED_LOCK_WITH_KEY ('\uD83D','\uDD10'),
    KEY                  ('\uD83D','\uDD11'),
    LOCK                 ('\uD83D','\uDD12'),
    UNLOCK	             ('\uD83D','\uDD13'),
    BELL                 ('\uD83D','\uDD14'),
    NO_BELL              ('\uD83D','\uDD15'),
    BOOKMARK             ('\uD83D','\uDD16'),
    LINK                 ('\uD83D','\uDD17'),
    RADIO_BUTTON         ('\uD83D','\uDD18'),
    END                  ('\uD83D','\uDD1A'),
    ON                   ('\uD83D','\uDD1B'),
    TOP                  ('\uD83D','\uDD1D'),
    UNDERAGE             ('\uD83D','\uDD1E'),
    KEYCAP_TEN           ('\uD83D','\uDD1F'),


    // Chart,
    BAR_CHART                ('\uD83D', '\uDCCA'),
    LINE_CHART_UPWARDS_TREND ('\uD83D', '\uDCC8'),
    STOCK_CHART              ('\uD83D', '\uDDE0'),

    // Arrows,
    LEFTWARDS_ARROW                 (null, '\u2190'),
    UPWARDS_ARROW                   (null, '\u2191'),
    RIGHTWARDS_ARROW                (null, '\u2192'),
    DOWNWARDS_ARROW                 (null, '\u2193'),
    LEFT_RIGHT_ARROW                (null, '\u2194'),
    UP_DOWN_ARROW                   (null, '\u2195'),
    LEFTWARDS_ARROW_WITH_HOOK       (null, '\u21a9'),
    UPWARDS_ARROW_TO_BAR            (null, '\u2912'),
    DOWNWARDS_ARROW_TO_BAR          (null, '\u2913'),
    TWISTED_RIGHTWARDS_ARROWS       ('\uD83D','\uDD00'),
    ARROW_REPEAT                    ('\uD83D','\uDD01'),
    ARROW_REPEAT_ONE                ('\uD83D','\uDD02'),
    ARROWS_CLOCKWISE                ('\uD83D','\uDD03'),
    ARROWS_COUNTERCLOCKWISE         ('\uD83D','\uDD04'),
    SOON_WITH_RIGHTWARDS_ARROW_ABOVE('\uD83D','\uDD1C'),

    // Object,
    BLACK_SCISSORS      (null, '\u2702'),
    ENVELOPE            (null, '\u2709'),
    PENCIL              (null, '\u270F'),
    BLACK_NIB           (null, '\u2712'),
    BRIEFCASE           ('\ud83d','\uDCBC'),
    FLOPPY_DISK         ('\ud83d','\uDCBE'),
    FILE_FOLDER         ('\ud83d','\uDCC1'),
    OPEN_FILE_FOLDER    ('\ud83d','\uDCC2'),
    TEAR_OFF_CALENDAR   ('\uD83D','\uDCC6'),
    CLIPBOARD           ('\uD83D','\uDCCB'),
    ROUND_PUSHPIN       ('\uD83D','\uDCCD'),
    PAPERCLIP           ('\ud83d','\uDCCE'),
    STRAIGHT_RULER      ('\uD83D','\uDCCF'),
    TRIANGULAR_RULER    ('\ud83d','\uDCD0'),
    WRENCH              ('\uD83D','\uDD27'),
    DOOR                ('\uD83D','\uDEAA'),

    // Dingbats group,
    WHITE_HEAVY_CHECK_MARK            (null, '\u2705'),
    RAISED_FIST                       (null, '\u270A'),
    RAISED_HAND                       (null, '\u270B'),
    VICTORY_HAND                      (null, '\u270C'),
    HEAVY_CHECK_MARK                  (null, '\u2714'),
    HEAVY_MULTIPLICATION_X            (null, '\u2716'),
    EIGHT_SPOKED_ASTERISK             (null, '\u2733'),
    EIGHT_POINTED_BLACK_STAR          (null, '\u2734'),
    CROSS_MARK                        (null, '\u274C'),
    NEGATIVE_SQUARED_CROSS_MARK       (null, '\u274E'),
    BLACK_QUESTION_MARK_ORNAMENT      (null, '\u2753'),
    WHITE_QUESTION_MARK_ORNAMENT      (null, '\u2754'),
    WHITE_EXCLAMATION_MARK_ORNAMENT   (null, '\u2755'),
    HEAVY_EXCLAMATION_MARK_SYMBOL     (null, '\u2757'),
    HEAVY_BLACK_HEART                 (null, '\u2764'),
    HEAVY_PLUS_SIGN                   (null, '\u2795'),
    HEAVY_MINUS_SIGN                  (null, '\u2796'),
    HEAVY_DIVISION_SIGN               (null, '\u2797'),
    BLACK_RIGHTWARDS_ARROW            (null, '\u27A1'),
    CURLY_LOOP                        (null, '\u27B0'),

    // Means of transport,
    AIRPLANE                          (null, '\u2708'),
    ROCKET                            ('\uD83D', '\uDE80'),
    RAILWAY_CAR                       ('\uD83D', '\uDE83'),
    HIGH_SPEED_TRAIN                  ('\uD83D', '\uDE84'),
    HIGH_SPEED_TRAIN_WITH_BULLET_NOSE ('\uD83D', '\uDE85'),
    METRO                             ('\uD83D', '\uDE87'),
    STATION                           ('\uD83D', '\uDE89'),
    BUS                               ('\uD83D', '\uDE8C'),
    BUS_STOP                          ('\uD83D', '\uDE8F'),
    AMBULANCE                         ('\uD83D', '\uDE91'),
    FIRE_ENGINE                       ('\uD83D', '\uDE92'),
    POLICE_CAR                        ('\uD83D', '\uDE93'),
    TAXI                              ('\uD83D', '\uDE95'),
    AUTOMOBILE                        ('\uD83D', '\uDE97'),
    RECREATIONAL_VEHICLE              ('\uD83D', '\uDE99'),
    DELIVERY_TRUCK                    ('\uD83D', '\uDE9A'),
    SHIP                              ('\uD83D', '\uDEA2'),
    SPEEDBOAT                         ('\uD83D', '\uDEA4'),
    BICYCLE                           ('\uD83D', '\uDEB2'),

    // Transport and map symbols Group,
    HORIZONTAL_TRAFFIC_LIGHT    ('\uD83D', '\uDEA5'),
    CONSTRUCTION_SIGN           ('\uD83D', '\uDEA7'),
    POLICE_CARS_REVOLVING_LIGHT ('\uD83D', '\uDEA8'),
    TRIANGULAR_FLAG_ON_POST     ('\uD83D', '\uDEA9'),
    NO_ENTRY_SIGN               ('\uD83D', '\uDEAB'),
    SMOKING_SYMBOL              ('\uD83D', '\uDEAC'),
    NO_SMOKING_SYMBOL           ('\uD83D', '\uDEAD'),
    PEDESTRIAN                  ('\uD83D', '\uDEB6'),
    MENS_SYMBOL                 ('\uD83D', '\uDEB9'),
    WOMENS_SYMBOL               ('\uD83D', '\uDEBA'),
    RESTROOM                    ('\uD83D', '\uDEBB'),
    BABY_SYMBOL                 ('\uD83D', '\uDEBC'),
    TOILET                      ('\uD83D', '\uDEBD'),
    WATER_CLOSET                ('\uD83D', '\uDEBE'),
    BATH                        ('\uD83D', '\uDEC0'),

    // Weather,
    CLOUD                       (null, '\u2601'),
    UMBRELLA_WITH_RAIN_DROPS    (null, '\u2614'),
    HIGH_VOLTAGE_SIGN           (null, '\u26A1'),
    SNOWMAN_WITHOUT_SNOW        (null, '\u26C4'),
    SUN_BEHIND_CLOUD            (null, '\u26C5'),
    SNOWFLAKE                   (null, '\u2744'),
    DROPLET                     ('\ud83d', '\uDCA7'),
    WIND_BLOW                   ('\ud83d', '\uDCA8'),
    FOGGY                       ('\uD83C', '\uDF01'),
    CLOSED_UMBRELLA             ('\uD83C', '\uDF02'),
    SUN_WITH_FACE               ('\uD83C', '\uDF1E'),
    THERMOMETER                 ('\uD83C', '\uDF21'),


    // Map,
    EARTH_GLOBE_EUROPE_AFRICA   ('\uD83C', '\uDF0D'),
    EARTH_GLOBE_EUROPE_AMERICAS ('\uD83C', '\uDF0E'),
    EARTH_GLOBE_EUROPE_ASIA     ('\uD83C', '\uDF0F'),
    GLOBE_WITH_MERIDIANS        ('\uD83C', '\uDF10'),

    // Hand,
    WHITE_RIGHT_POINTING_BACKHAND_INDEX  ('\uD83D', '\uDC49'),
    WAVING_HAND_SIGN                     ('\uD83D', '\uDC4B'),
    THUMBS_UP_SIGN                       ('\uD83D', '\uDC4D'),

    // Others,
    INFORMATION_SOURCE                   (null, '\u2139'),
    BLACK_RIGHT_POINTING_DOUBLE_TRIANGLE (null, '\u23E9'),
    BLACK_RIGHT_POINTING_TRIANGLE        (null, '\u25B6'),
    SPARKLES                             (null, '\u2728'),
    SPARKLE                              (null, '\u2747'),
    HUNDRED_POINTS_SYMBOL                ('\uD83D', '\uDCAF'),
    BACK_WITH_LEFTWARDS_ARROW_ABOVE      ('\uD83D', '\uDD19'),
    LARGE_ORANGE_DIAMOND                 ('\uD83D', '\uDD36');

    Character firstChar;
    Character secondChar;

    Emoji(Character firstChar, Character secondChar) {
        this.firstChar = firstChar;
        this.secondChar = secondChar;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        if (this.firstChar != null) {
            sb.append(this.firstChar);
        }
        if (this.secondChar != null) {
            sb.append(this.secondChar);
        }

        return sb.toString();
    }
}
